//Leo Zheng
//Oct 17th 2015
//Bagels

/*The is program is designed for the user to play Bagels Game via console interaction 
  and will report the statistics of results for all games played. The program will
  generate a random integer number and let the user to guess. Hint is given after each 
  guess to help to lead the user to the correct answer */

import java.util.*;
import java.io.*;

public class Bagels {
   public static void main(String[] args){
      // print introductory message for the user   
      introBagels();
      int totalgames = 0;
      int totalguess = 0;
      int bestgame = 0;
      String nextplay = "Yes";
      Scanner console = new Scanner(System.in);
  
      do {
         //ask the user to play one game and return the number of guesses made by the user    
         int n_guess = playBagels(console);
         //accumlate the total numbers of games and guesses
         totalgames++;
         totalguess += n_guess;
         //store the minimum n_guess as best game
         if (n_guess < bestgame || totalgames == 1) {
            bestgame = n_guess; 
         }
         
         //ask the user if he or she wants to play another game
         //a new game will start if user input a word that starts with Y or y
         System.out.print("Do you want to play again? ");
         nextplay = console.next();
         
      }while(nextplay.startsWith("Y") || nextplay.startsWith("y"));
      
      //report the results of games played
      reportResults(totalgames,totalguess,bestgame);
      
   }

   // a method that prints the guide of Game Bagels for the user at the beginning
   public static void introBagels(){
      System.out.println("Welcome to CSE 143x Bagels!");
      System.out.println("I'll think up a number for you to guess.");
      System.out.println("Each digit will be between 1 and 9.");
      System.out.println("Try to guess my number, and I'll say \"fermi\"");
      System.out.println("for each digit you get right and in the right");
      System.out.println("place, and \"pica\" for each digit you get right");
      System.out.println("that is in the wrong place.");
      System.out.println();
   }
   
   // ask the user to play one Bagels Game and return the number of guesses made by the user
   // the console input by the user is fed to the method
   public static int playBagels(Scanner console){
      
      int nguess = 0;
      System.out.print("How many digits this time? ");
      int n = console.nextInt();
      //generate a random number for the user to guess
      int[] ans = generateAns(n);
      // ask for first try
      System.out.println();
      System.out.print("Your guess? ");
      // read an integer number from console and store it as an array of digits
      int[] guess = getGuessArray(console,n);
      // test the first try and ready to accept more tries
      if (Arrays.equals(guess,ans)) {
         System.out.println("You got it right in 1 guess"); 
         nguess = 1;}
      else {
         nguess =1;
         //repeatedly ask for a new try and give a hint until the correct answer is input
         while(!Arrays.equals(guess,ans) || nguess > 9999){
            giveHint(guess,ans);
            System.out.print("Your guess? ");
            guess = getGuessArray(console,n);
            nguess++;
        
         }
         System.out.println("You got it right in "+nguess+ " guesses");
      }
      return nguess;   
        
   }
   
   //generate a random number digit by digit 
   // each digit is btw 1 and 9 inclusive, the input arg is number of digits
   public static int[] generateAns(int ndigit) {
      int[] answer = new int[ndigit];
      Random rand = new Random();
      for(int i=0;i < ndigit; i++) {
         answer[i] = rand.nextInt(9)+1;
      }
      return answer;
   
   }
   
   //read the integer token from console and store it as array with each element a digit
   //the input arg are console reading from user and number of digits
   public static int[] getGuessArray(Scanner console,int n){
      int guess = console.nextInt();
      int[] guessarr = new int[n];
      for(int i=0; i < n; i++){
         guessarr[n-i-1] = guess % 10;
         guess /= 10;
      }
      return guessarr;
   }
   
   // throw the user a hint to help lead to the correct answer
   // the hint is generated by comparing user's guess and the correct answer digit by digit
   public static void giveHint(int[] guess, int[] ans){
      int n=ans.length;
      //make duplicate copies of ans and guess for comparison
      // avoid changing values in original ans and guesss arrays
      int[] newans = Arrays.copyOf(ans,n);
      int[] newguess = Arrays.copyOf(guess,n);
      int fermipica = 0;
      //print out "fermi" for the correc digit in the right place
      // and mark the "fermi" digits as -1 
      for(int i = 0; i < n; i++) { 
         if (newguess[i] == newans[i]) {
            System.out.print("fermi ");
            newguess[i] = -1;
            newans[i] = -1;
            fermipica++;}
         }
       
      // print out "pica" for the correct digit in the wrong place
      for(int i = 0;i < n; i++) {
         // only go through digits that >0 to avoid the fermi digits marked as -1
         if (newguess[i] > 0){
            // return the index of first element in newans that equals newguess[i]
            int index = elementSearch(newans,newguess[i]);
            if (index >= 0 ) {
               System.out.print("pica ");
               fermipica++;
               //mark the "pica" element
               newans[index] = -1;
            }    
         }   
      }      
      //report "bagels" if neither pica nor fermi is found
      if (fermipica == 0) {
         System.out.print("bagels");}   
      
      System.out.println();  
   }
   
   // return the index of first element in arr that equals wanted
   public static int elementSearch(int[] arr, int wanted){
      for(int i=0; i< arr.length; i++) {
         if (arr[i] == wanted) {
            return i;
         }
      
      }
      // -1 is returned if no match is found
      return -1;
   }
   
   // report the results of all games played    
   public static void reportResults(int totalgames,int totalguess,int bestgame) {
      System.out.println("Overall results:");
      System.out.println("    total games   = "+totalgames);
      System.out.println("    total guesses = "+ totalguess);
      System.out.printf("    guesses/game  = %.1f\n",(double) totalguess/totalgames);
      System.out.println("    best game     = "+ bestgame);
      System.out.println(); 
   }

}